import smtplib
import datetime as dt
import random 
import pandas as pd
#for image
# from email.mime.multipart import MIMEMultipart
# from email.mime.image import MIMEImage


my_email = "akashgupta7965@gmail.com"
password = "Your Password which generated by Google(by searching app password generate)"
# msg = MIMEMultipart()

# img_path = "download (2).jpeg"


# Attach the image
# with open(image_path, 'rb') as image_file:
#     img = MIMEImage(image_file.read())
#     img.add_header('Content-ID', '<image>')
#     msg.attach(img)

# img = Image.open(r"python\automate email send\download (2).jpeg")
# show = img.show()
today = dt.datetime.now()
today_month_day = (today.month,today.day)

data = pd.read_csv("birthdays.csv")
# birthdays_dict = {
#     (birthday_manth,birthday_day): data_row
# }
birthdays_dict = {(data_row["month"], data_row["day"]):data_row for (index,data_row) in data.iterrows()}
if today_month_day in birthdays_dict:
    birthday_person = birthdays_dict[today_month_day]
    file_path = f"letter_{random.randint(1,3)}.txt"
    with open(file_path) as letter_file:
        contents = letter_file.read()
        contents=contents.replace("[NAME]",birthday_person['name'])

    # current_weekday=(today.weekday)
    # with open(r"python\automate email send\quotes.txt", 'r') as quotes:
    #     data=quotes.read().splitlines()
    #     random_data = random.choice(data)
    #     # print(random_data)
    

    with smtplib.SMTP("smtp.gmail.com") as connection:
        connection.starttls()
        connection.login(user=my_email, password=password)
        connection.sendmail(from_addr=my_email,
                            to_addrs=birthday_person["email"],
                            msg=f"Subject:Happy Birthday\n\n {contents}\n\n By Akash")
        print("email sent successfully")
        connection.close()
    

    
    
    